---
title: "Stat 850 Project Proposal"
format: html
editor: visual
Authors: Mahyar Madarshahain, Jing Wang
---

## Instructions

Each member of your team should modify this document in some way and push their modifications to the repository in a separate commit. This will ensure that you have set your repository up in a way that ensures all group members are working with the same repository.

Please ensure that you have set your git name and email address on your computer by **modifying** the following commands and running them in the terminal:

```         
git config --global user.name "Mona Lisa"
git config --global user.email "mona@lisa.com"
```

In the proposal as in the final report, all of your code chunks should be set so that `echo = F`, which prevents the code from being printed in the report. You should also set `message = F, warning = F`, which will reduce the amount of additional output which is present in the report. You can customize the execution of code in quarto by using additional options, some of which are detailed [here](https://quarto.org/docs/computations/execution-options.html).

## Data

### Source

The data we are using in this project comes from \[<https://www.arts.gov/impact/research/arts-data-profile-series/adp-31/data-tables>\].

If you cannot link directly to the data file, then you need to additionally describe how someone could acquire the same data:

> You can download the data directly using \[<https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-09-27/artists.csv>\]

```{r}
url <- "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-09-27/artists.csv"

# Read the data from the URL into a data frame
artists_data <- read.csv(url)
head(artists_data)
```

Provide some code to read in the data (either stored in the repository or read in directly from the source).

### Description

The dataset provides insights into the presence and concentration of Hispanic architects in different states, highlighting variations in workforce demographics and professional diversity across the United States.

It was collected from \[mention data source and any specific details about the dataset\].


Here is a data dictionary showing each variable, the type of variable, units, and range of values that are possible:

Note: this is an example table, please modify to actually match your data. Ensure that all of the same information is represented.

<<<<<<< HEAD
| variable \| class \| description \|
| state \| character \| This variable represents the U.S. state where the data was collected\|
| race \| character \| This variable specifies the racial or ethnic category of the workforce being analyzed\|
| type \| character \| This variable indicates the type of profession or occupation for which the data is recorded \|
| all_workers_n \| double \| This numeric variable represents the total number of workers in the specified state and occupation \|
| artists_n \| double \| This numeric variable signifies the number of artists within the same state and occupation\|
| artists_share \| double \| This numeric variable expresses the share or proportion of artists among all workers in the occupation within the particular state\|
| location_quotient \| double \| Location quotient is a numerical measure used to assess the concentration of a particular occupation in a specific geographical area\|

| 
| labor force share. For example, an LQ of 1.2 indicates that the state's labor force in an occupation is 20 percent greater than the occupation's national labor force share. An LQ of 0.8 indicates that the state's labor force in an occupation is 20 percent below the occupation's national labor force share. \|
=======
| variable          | class     | description                             |
| state             | character | This variable represents the U.S. state where the data was collected|
| race              | character | This variable specifies the racial or ethnic category of the workforce being analyzed|
<<<<<<< HEAD
| type              | character | This variable indicates the type of profession or occupation for which the data is recorded                                                                                                                                                                                                                                                                                                                                                                                              |
=======
| type              | character | This variable indicates the type of profession or occupation for which the data is recorded                                                                                                                                                                                                                                                                                                                                                                                                                  |
>>>>>>> 747e090b05eb830735262ce82d035672014eb74c
| all_workers_n     | double    | This numeric variable represents the total number of workers in the specified state and occupation                                                                                                                                                                                                                                                                                                                                                                                                                 |
| artists_n         | double    | This numeric variable signifies the number of artists within the same state and occupation                                                                                                                                                                                                                                                                                                                                                                                                                     |
| artists_share     | double    | artist share                                                                                                                                                                                                                                                                                                                                                                                                                     |
| location_quotient | double    | Location quotients (LQ) measure an artist occupation's concentration in the labor force, relative to the U.S. labor force share. For example, an LQ of 1.2 indicates that the state's labor force in an occupation is 20 percent greater than the occupation's national labor force share. An LQ of 0.8 indicates that the state's labor force in an occupation is 20 percent below the occupation's national labor force share. |
>>>>>>> 5160a82ddff9d56589b842bef079e108f76909c7

## Project Goals

Describe why this data is interesting and what you hope to do with it.

We will use \[dataset\](<https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-09-27/artists.csv>) to explore the following topics:

-   The top 10 state /territory has the highest number of artists, as indicated by the location quotient.
-   Are there any states with a location quotient significantly below 1.0 for artists?
-   What is the overall distribution of artist types across different states or territories?
-   Is there a correlation between the percentage of artists in a state (artists_share) and the state's number of workers?
-   How does the racial diversity of artists vary across different states or territories? Are there states with a more diverse artist population than others?
-   Are there any states where the racial composition of artists is significantly different from the overall racial composition of the state's population, and what might explain this difference?

We expect to create

-   Several summary tables
-   Data visualization (age difference distribution, time series, director influence...)
-   Some interesting findings (race, number of artists, states, ...)
-   ...

## Division of Labor
During the whole project, Mahyar and Jing will collaborate closely and help each other using R and Python.

- Task 1: Clean and preprocess dataset
  ** Mahyar will set up the the environment, prepare the basic visualization, clean and preprocess the dataset using python
  ** Jing Wang will set up the the environment, prepare the basic visualization, clean and preprocess the dataset using R
  
-Task 2: exploring the data, identifying trends, and creating visualizations


We will work together to cleaning and preprocessing the dataset.

We will work together to focus on exploring the data, identifying trends, and creating visualizations

We will work together to creat interactive graphics to enhance data exploration.

We will work together for creating the project report and presentation

## Additional Comments

Up to now there is no concern about the project.
